services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: senai-backend

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    depends_on:
      - chroma

    volumes:
      - ./backend:/app

  chroma:
    image: chromadb/chroma:latest

    container_name: senai-chroma

    ports:
      - "8001:8000"

    volumes:
      - chroma_data:/chroma/chroma

volumes:
  chroma_data: