"""added new models

Revision ID: 86d5f16689d5
Revises: 1833adf83395
Create Date: 2026-06-12 10:13:07.960702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86d5f16689d5'
down_revision: Union[str, Sequence[str], None] = '1833adf83395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.String(), nullable=True),
    sa.Column('agent_reasoning_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('proposed_content', sa.String(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_email_id'), 'actions', ['email_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('performed_by', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_table('web_intelligence_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('target_entity', sa.String(), nullable=True),
    sa.Column('scraped_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_intelligence_cache_source_url'), 'web_intelligence_cache', ['source_url'], unique=False)
    op.create_index(op.f('ix_web_intelligence_cache_target_entity'), 'web_intelligence_cache', ['target_entity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_web_intelligence_cache_target_entity'), table_name='web_intelligence_cache')
    op.drop_index(op.f('ix_web_intelligence_cache_source_url'), table_name='web_intelligence_cache')
    op.drop_table('web_intelligence_cache')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_actions_email_id'), table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###
