"""contact account fields

Revision ID: d6f7ed817cab
Revises: 097edb43ad91
Create Date: 2026-06-10 09:36:40.565865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6f7ed817cab'
down_revision: Union[str, Sequence[str], None] = '097edb43ad91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('subscription_tier', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('billing_status', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('overdue_invoices', sa.Integer(), nullable=True))
    op.add_column('contacts', sa.Column('vip_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'vip_status')
    op.drop_column('contacts', 'overdue_invoices')
    op.drop_column('contacts', 'billing_status')
    op.drop_column('contacts', 'subscription_tier')
    # ### end Alembic commands ###
